Add make target tag-release to bump version and zero release, commit, and tag.

diff --git a/rel-eng/Makefile.git b/rel-eng/Makefile.git
--- a/rel-eng/Makefile.git
+++ b/rel-eng/Makefile.git
@@ -32,8 +32,10 @@ EXISTING_SRC_RPM := $(wildcard *.src.rpm)
 
 ifdef KEEP_VERSION
 BUMP_VERSION := check-keep-version
+BUMP_RELEASE := check-keep-version
 else
 BUMP_VERSION := bump-version
+BUMP_RELEASE := bump-release
 endif
 
 
@@ -51,12 +53,19 @@ help :
 		cat $(README_FILE) ; \
 		else echo "The README file with help was not found."; fi
 
-tag-minor-release : $(BUMP_VERSION)
+tag-release : RELEASE_TYPE = release
+tag-release : $(BUMP_VERSION) x-tag-release
+
+tag-minor-release : RELEASE_TYPE = minor release
+tag-minor-release : $(BUMP_RELEASE) x-tag-release
+
+x-tag-release :
 	@BUMPED_VERSION=`rpm -q $(RPMBUILD_CURDIR) --define 'dist %{undefined}' --qf '%{version}-%{release}\n' --specfile $(SPECFILE) | head -1`; \
+		if test -z "$$BUMPED_VERSION" ; then echo "Failed to bump the version (got empty from specfile [$(SPECFILE)])." ; exit 1 ; fi ; \
 		BUMPED_VERSION_MESSAGE="Tagging package [$(NAME)] version [$$BUMPED_VERSION] in directory [$(GIT_PREFIX)]." ; \
 		echo "$$BUMPED_VERSION $(GIT_PREFIX)" > $(THIS_DIR)packages/$(NAME) ; \
 		git add $(THIS_DIR)packages/$(NAME) ; \
-		git commit -m "Automatic commit of package [$(NAME)] minor-release [$$BUMPED_VERSION]." . $(THIS_DIR)packages/$(NAME) \
+		git commit -m "Automatic commit of package [$(NAME)] $(RELEASE_TYPE) [$$BUMPED_VERSION]." . $(THIS_DIR)packages/$(NAME) \
 		&& git tag -m "$$BUMPED_VERSION_MESSAGE" $(NAME)-$$BUMPED_VERSION HEAD
 
 test-srpm : $(TEST_GIT_ARCHITE_TO_TAR_GZ) test-setup-specfile
@@ -85,10 +94,20 @@ test-setup-specfile :
 bump-version : test-version
 	@for version_file in $(VERSION_FILE) $(VERSION_FILES) ; do \
 		ORIG_VERSION=`cat $$version_file` ; \
+		BUMPED_VERSION=`perl -lane '$$F[0] =~ s!(\S*)(^|\.)(\d+)(\.|%|$$)!$$1.$$2 . ($$3 + 1) . $$4!e; $$F[1] =~ s!(^|\.)((\d|\.)+)(\.|%|$$)!$$1 . 0 .  $$4!e; print "@F";' $$version_file` ; \
+		if test -z "$$BUMPED_VERSION" ; then echo "Failed to bump the version [$$ORIG_VERSION] (got empty)." ; exit 1 ; fi ; \
+		if test "x$$ORIG_VERSION" == "x$$BUMPED_VERSION" ; then echo "Failed to bump the version [$$ORIG_VERSION] (got the same)." ; exit 1 ; fi ; \
+		echo "Bumping $$version_file from [$$ORIG_VERSION] to [$$BUMPED_VERSION] in [$$version_file]." ; \
+		echo $$BUMPED_VERSION > $$version_file ; \
+	done
+
+bump-release : test-version
+	@for version_file in $(VERSION_FILE) $(VERSION_FILES) ; do \
+		ORIG_VERSION=`cat $$version_file` ; \
 		BUMPED_VERSION=`perl -pe 's!^(\S+\s(.+\.)*)(\d+)([\.%].+)?$$!$$1 . ($$3 + 1) . $$4!e' $$version_file` ; \
 		if test -z "$$BUMPED_VERSION" ; then echo "Failed to bump the version [$$ORIG_VERSION] (got empty)." ; exit 1 ; fi ; \
 		if test "x$$ORIG_VERSION" == "x$$BUMPED_VERSION" ; then echo "Failed to bump the version [$$ORIG_VERSION] (got the same)." ; exit 1 ; fi ; \
-		echo "Bumping $$version_file from [$$ORIG_VERSION] to [$$BUMPED_VERSION]." ; \
+		echo "Bumping $$version_file from [$$ORIG_VERSION] to [$$BUMPED_VERSION] in [$$version_file]." ; \
 		echo $$BUMPED_VERSION > $$version_file ; \
 	done
 
