1348575 - rhn-charsets is meant to be run only under root user

diff --git a/backend/satellite_tools/rhn-charsets b/backend/satellite_tools/rhn-charsets
--- a/backend/satellite_tools/rhn-charsets
+++ b/backend/satellite_tools/rhn-charsets
@@ -1,5 +1,10 @@
 #!/bin/bash
 
+if [ $UID != "0" ]; then
+  echo "ERROR: must be root to execute"
+  exit 1
+fi
+
 BACKEND=$( spacewalk-cfg-get db_backend )
 
 if [ $BACKEND == 'oracle' ]; then
